### PR TITLE
setup toplevel story-specific CustomElement entrypoints to avoid collisions in global customElements

### LINKED ISSUE #7: `design-system-imports.stories` tests crash when viewed in Storybook via browser
`_shared_customElements.ts` should be deprecated in favour of a generator function which can dynamically create wrapper CustomElement classes that have unique tag names bound to each story. This would be the more robust way of ensuring that there are no conflicts in the global `customElements` registry definitions.

However, this may be more complicated than the simple case since many components use slotted children; meaning that the rendering of child elements is occasionally the responsibility of the root shadow DOM rather than that of the containing component.

([via](https://github.com/neighbour-hoods/design-system-components/pull/3#discussion_r1312630480) #3)

### PR DESCRIPTION
**Pull request by pospi**
includes generic adapter logic to translate story `args` to props of the component unit under test.

Fixes #7

### CODE REVIEW

**Review by nick-stebbings — COMMENTED** [review]
I am having some rendering issues in the Storybook with certain components now that this has been refactored.

Is it the case that the components that these updated stories refer to were using the deleted `_shared_customElements.ts` file too? Can you take a look and see if they also need refactoring given these changes?

**Comment by pospi** [comment]
@nick-stebbings was that the only error, or are the more to take a look at?

**Comment by nick-stebbings** [comment]
@pospi Yeah I fixed one of them in the last commit, just a case of reimporting the components and registering.

**Comment by pospi** [comment]
In that case, ready to merge when you're happy.

**Pull request merged**
